# Generated by Django 3.1.5 on 2021-01-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField(max_length=5, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sys_city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=13, unique=True)),
                ('tax_number', models.CharField(max_length=9, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, unique=True)),
                ('date', models.DateTimeField()),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=4)),
                ('count', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'invoice_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tax_number', models.CharField(max_length=9)),
                ('national_id', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('payment_account', models.CharField(max_length=25)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sys_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'sys_tax_rate',
                'managed': False,
            },
        ),
    ]
