# Generated by Django 3.1.5 on 2021-01-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('is_admin', models.IntegerField()),
                ('is_active', models.IntegerField(default=True)),
            ],
            options={
                'db_table': 'sys_user',
                'managed': False,
            },
        ),
    ]
