# Generated by Django 3.1.5 on 2021-01-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0002_auto_20210122_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='postCode',
            new_name='post_code',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='nationalID',
            new_name='national_id',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='taxNumber',
            new_name='tax_number',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='dateFrom',
            new_name='date_from',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='dateTo',
            new_name='date_to',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='taxRate',
            new_name='tax_rate',
        ),
        migrations.RenameField(
            model_name='mycompany',
            old_name='nationalID',
            new_name='national_id',
        ),
        migrations.RenameField(
            model_name='mycompany',
            old_name='taxNumber',
            new_name='tax_number',
        ),
    ]
