# Generated by Django 3.1.5 on 2021-01-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0003_auto_20210122_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='created_by',
        ),
    ]
